### ISSUE TITLE
Is *_sub file necessary?

### ISSUE THREAD

**Issue by yuksk** [yuksk/SIDAM#25]
In the next version (9.7.0), a parameter `noavg` will be added to `SIDAMLoadData()`. When `noavg = 1`, the forward and backward sweeps of spectroscopic data (.dat and .3ds) are loaded without being averaged. (An equivalent shortcut has been implemented without documentation. It will be explicitly included.)

I'm wondering if the "_sub" wave, which is "forward sweep" - "backward sweep", is necessary. I plan to remove it or to add a preference to decide if you use it. If you have any opinion, please tell me here.

**Comment by tmcda** [comment]
Although I have sometimes used "_sub" waves, I think "_sub" is not necessary, because we can easily obtain "_sub" by just taking the difference of "_forward" and "_backward" if needed.

**Comment by butlercj** [comment]
I have never used *_sub objects. I support removing the creation of *_sub objects, and I support using the `noavg` argument for loading *_fwd and *_bwd objects as described above.

**Comment by yuksk** [comment]
The "_sub" file is no longer created in v9.7.0 as no one uses it. If you need it for some reason, please use the `noavg` argument to create waves of forward and backward sweeps and calculate the difference between them.
