### ISSUE TITLE
Syncing of layers of multiple 3d data objects

### ISSUE THREAD

**Issue by butlercj** [yuksk/SIDAM#26]
The dialog box for syncing of displayed layers for multiple 3d data objects does not always list all the data objects that can reasonably be synced. Are objects only sync-able if they share exactly the same size (xpixels, ypixels, layers) as the current object? A user's naive expectation may be that all objects with the same number of layers can be synced.

**Comment by yuksk** [comment]
As you expect, objects with the same number of layers can be synced. A limitation (design) of the sync feature is that an object can belong to one sync group. So, objects belonging to a sync group are not listed in the dialog box. If you want to add a new object to an existing sync group, open the sync dialog box from a window that is already synced.
