### ISSUE TITLE
Fail to compile SIDAM ver.9.7.0 on Igor Pro ver.8.0.4.2

### ISSUE THREAD

**Issue by SatoAku** [yuksk/SIDAM#37]
When I compiled SIDAM ver 9.7.0 on Igor Pro ver.8.0.4.2, an error was happened.
The error message is 
"Function Compilation Error
 expected a keyword or an object name
 Error in SIDAM_HDF5.ipf:SIDAMLoadHDF5
  HDF5OpenFile/R/Z fileID as pathStr".

**Comment by yuksk** [comment]
Thanks for your report. Igor Pro 8 requires an extension to handle HDF5 files. Copy an extension file to a designated folder as follows, please.

- 32 bit
Copy `Igor Pro 8 Folder/More Extensions/File Loaders/HDF5.xop` to `Igor Pro 8 User Files/Igor Extensions`

- 64 bit
Copy `Igor Pro 8 Folder/More Extensions (64-bit)/File Loaders/HDF5-64.xop` to `Igor Pro 8 User Files/Igor Extensions (64-bit)`
