### ISSUE TITLE
Error when compiling on IGOR9 (MAC)

### ISSUE THREAD

**Issue by mpardo0** [yuksk/SIDAM#41]
An error saying "SIDAM" folder is not found appears when trying to compile on MAC version of IGOR9

**Comment by yuksk** [comment]
I can not reproduce such an error, especially because I do not have a Mac.
Can you tell me what is shown in the history window when you execute the following?
`GetFileFolderInfo SpecialDirPath("Igor Pro User Files", 0, 0, 0)+ "User Procedures:SIDAM"`

**Comment by mpardo0** [comment]
It opens a window in "Documents->Wavemetrics-> IgorPro9 Userfiles->User Procedures" but this folder is empty because in mac the macro files are directly located in "Applications-> IgorPro9" which is different folder. Could this be the reason for the error? When I click in "MACRO--> SIDAM" is IGOR trying to find the folder in this path  "Documents->Wavemetrics-> IgorPro9 Userfiles->User Procedures"?

After I click in cancel in the window that appeared the history shows the message V_Flag= -1

**Comment by yuksk** [comment]
The result seems to indicate that you did not install the macro as instructed. If you still have the same error even if you follow the instruction, I will think about how to diagnose the error.

**Comment by yuksk** [comment]
According to the [manual](https://www.wavemetrics.net/doc/IgorMan.pdf#page=103), there is no big difference between Windows and Mac for placing user procedure files. Again, please follow the instruction in [readme.md](https://github.com/yuksk/SIDAM) and tell me if you still have the same error.

**Comment by mpardo0** [comment]
Thank you, it looks like I was placing the files in the wrong folder. The problem is solved now.
