### ISSUE TITLE
Unknown text encoding error when uploading Nanonis files

### ISSUE THREAD

**Issue by mtenorio1995** [yuksk/SIDAM#67]
SIDAM macro is successfully loaded into Igor Pro (version 9). But when opening any *.sxm, *.dat, *.nsp file, this message appears: 'While executing ConvertTextEncoding, the following error occurred: Unknown text encoding'.
Files are loaded after this message but with no information inside ('NaN' or '0 bytes' files).

Thank you!!

**Comment by yuksk** [comment]
Seems like the same as #66

**Comment by mtenorio1995** [comment]
I followed the recommendations given in #66 and now the problem is solved. Thank you very much!
